03:44:42 PM: DEBUG [logger_base.py:12] Prueba debug
04:29:35 PM: ERROR [CursorDelPool.py:23] Ocurrio un error, realizando rollback: 'psycopg2.extensions.cursor' object has no attribute 'excute' <class 'AttributeError'> <traceback object at 0x7b79b5bbf780>
04:29:48 PM: ERROR [CursorDelPool.py:23] Ocurrio un error, realizando rollback: relation "inventario" does not exist
LINE 1: SELECT * FROM inventario
                      ^
 <class 'psycopg2.errors.UndefinedTable'> <traceback object at 0x7d04ce9ee180>
04:30:09 PM: INFO [CursorDelPool.py:35] [(1, 'Clorox', 'Limpiador Multiusos', 20000.0, 2)]
04:42:36 PM: INFO [Objetos.py:59] 
            ID producto: 1, Nombre: Clorox, 
            Descripcion: Limpiado multiusos, Precio: 20000.0,
            Cantidad: 5
        
07:28:48 PM: ERROR [CursorDelPool.py:23] Ocurrio un error, realizando rollback: syntax error at or near "SELEC"
LINE 1: SELEC * FROM objetos ORDER BY id_producto
        ^
 <class 'psycopg2.errors.SyntaxError'> <traceback object at 0x7c99c85fde80>
07:28:56 PM: INFO [ObjetoDao.py:60] 
            ID producto: 1, Nombre: Clorox, 
            Descripcion: Limpiador Multiusos, Precio: 20000.0,
            Cantidad: 2
        
